package lt.vu.mybatis.model;

public class Ingredient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.INGREDIENT.ID
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.INGREDIENT.NAME
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.INGREDIENT.ID
     *
     * @return the value of PUBLIC.INGREDIENT.ID
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.INGREDIENT.ID
     *
     * @param id the value for PUBLIC.INGREDIENT.ID
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.INGREDIENT.NAME
     *
     * @return the value of PUBLIC.INGREDIENT.NAME
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.INGREDIENT.NAME
     *
     * @param name the value for PUBLIC.INGREDIENT.NAME
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return String.format("%s[id=%d]", getClass().getSimpleName(), getId());
    }
}