package lt.vu.mybatis.model;

public class MealIngredient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEAL_INGREDIENT.MEALS_ID
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    private Integer mealsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEAL_INGREDIENT.INGREDIENTS_ID
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    private Integer ingredientsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEAL_INGREDIENT.MEALS_ID
     *
     * @return the value of PUBLIC.MEAL_INGREDIENT.MEALS_ID
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    public Integer getMealsId() {
        return mealsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEAL_INGREDIENT.MEALS_ID
     *
     * @param mealsId the value for PUBLIC.MEAL_INGREDIENT.MEALS_ID
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    public void setMealsId(Integer mealsId) {
        this.mealsId = mealsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEAL_INGREDIENT.INGREDIENTS_ID
     *
     * @return the value of PUBLIC.MEAL_INGREDIENT.INGREDIENTS_ID
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    public Integer getIngredientsId() {
        return ingredientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEAL_INGREDIENT.INGREDIENTS_ID
     *
     * @param ingredientsId the value for PUBLIC.MEAL_INGREDIENT.INGREDIENTS_ID
     *
     * @mbg.generated Mon Apr 13 23:20:18 EEST 2020
     */
    public void setIngredientsId(Integer ingredientsId) {
        this.ingredientsId = ingredientsId;
    }
}